[profile.default]
remapping = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/']
src = "src"
out = "out"
libs = ["lib"]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
